/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KutubxonaRouteImport } from './routes/kutubxona'
import { Route as ShifokorlarRouteImport } from './routes/shifokorlar'
import { Route as TashxisRouteImport } from './routes/tashxis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KutubxonaRoute = KutubxonaRouteImport.update({
  id: '/kutubxona',
  path: '/kutubxona',
  getParentRoute: () => rootRouteImport,
} as any)
const ShifokorlarRoute = ShifokorlarRouteImport.update({
  id: '/shifokorlar',
  path: '/shifokorlar',
  getParentRoute: () => rootRouteImport,
} as any)
const TashxisRoute = TashxisRouteImport.update({
  id: '/tashxis',
  path: '/tashxis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kutubxona': typeof KutubxonaRoute
  '/shifokorlar': typeof ShifokorlarRoute
  '/tashxis': typeof TashxisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kutubxona': typeof KutubxonaRoute
  '/shifokorlar': typeof ShifokorlarRoute
  '/tashxis': typeof TashxisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kutubxona': typeof KutubxonaRoute
  '/shifokorlar': typeof ShifokorlarRoute
  '/tashxis': typeof TashxisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kutubxona' | '/shifokorlar' | '/tashxis'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kutubxona' | '/shifokorlar' | '/tashxis'
  id: '__root__' | '/' | '/kutubxona' | '/shifokorlar' | '/tashxis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KutubxonaRoute: typeof KutubxonaRoute
  ShifokorlarRoute: typeof ShifokorlarRoute
  TashxisRoute: typeof TashxisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kutubxona': {
      id: '/kutubxona'
      path: '/kutubxona'
      fullPath: '/kutubxona'
      preLoaderRoute: typeof KutubxonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifokorlar': {
      id: '/shifokorlar'
      path: '/shifokorlar'
      fullPath: '/shifokorlar'
      preLoaderRoute: typeof ShifokorlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tashxis': {
      id: '/tashxis'
      path: '/tashxis'
      fullPath: '/tashxis'
      preLoaderRoute: typeof TashxisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KutubxonaRoute: KutubxonaRoute,
  ShifokorlarRoute: ShifokorlarRoute,
  TashxisRoute: TashxisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
